# Generated by Django 3.1.7 on 2026-10-06 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Espécie',
                'verbose_name_plural': 'Espécies',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('porte', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], max_length=1)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('D', 'Disponível'), ('A', 'Em Andamento'), ('C', 'Adotado')], default='D', max_length=1)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pets/')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RegistroMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Vacina', 'Vacina'), ('Consulta', 'Consulta'), ('Exame', 'Exame'), ('Medicação', 'Medicação'), ('Cirurgia', 'Cirurgia'), ('Castração', 'Castração'), ('Outro', 'Outro')], max_length=15)),
                ('data', models.DateField()),
                ('descricao_outro', models.CharField(blank=True, max_length=100)),
                ('descricao', models.TextField()),
                ('veterinario', models.CharField(blank=True, max_length=100)),
                ('clinica', models.CharField(blank=True, max_length=100)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_medicos', to='pets.pet')),
            ],
            options={
                'verbose_name': 'Registro Médico',
                'verbose_name_plural': 'Registros Médicos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racas', to='pets.especie')),
            ],
            options={
                'verbose_name': 'Raça',
                'verbose_name_plural': 'Raças',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='raca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='pets.raca'),
        ),
    ]
