# Generated by Django 3.1.7 on 2026-10-06 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacaoAdocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovada'), ('R', 'Rejeitada'), ('C', 'Cancelada')], default='P', max_length=1)),
                ('motivacao', models.TextField()),
                ('outros_animais', models.BooleanField(default=False)),
                ('tipo_moradia', models.CharField(choices=[('A', 'Apartamento'), ('C', 'Casa'), ('O', 'Outro')], max_length=1)),
            ],
            options={
                'verbose_name': 'Aplicação de Adoção',
                'verbose_name_plural': 'Aplicações de Adoção',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='CronogramaVisita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('local', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('A', 'Agendada'), ('R', 'Realizada'), ('C', 'Cancelada')], default='A', max_length=1)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-data', 'horario'],
            },
        ),
        migrations.CreateModel(
            name='TermoAdocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adocao', models.DateField()),
                ('termos_aceitos', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('aplicacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='termo_adocao', to='adocoes.aplicacaoadocao')),
            ],
            options={
                'verbose_name': 'Termo de Adoção',
                'verbose_name_plural': 'Termos de Adoção',
                'ordering': ['-data_adocao'],
            },
        ),
    ]
