# Generated by Django 3.1.7 on 2026-10-06 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adocoes', '0001_initial'),
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='termoadocao',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termo_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cronogramavisita',
            name='aplicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='adocoes.aplicacaoadocao'),
        ),
        migrations.AddField(
            model_name='aplicacaoadocao',
            name='adotante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicacoes_adocao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aplicacaoadocao',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicacoes_adocao', to='pets.pet'),
        ),
        migrations.AlterUniqueTogether(
            name='aplicacaoadocao',
            unique_together={('pet', 'adotante')},
        ),
    ]
