# Generated by Django 3.1.7 on 2026-10-01 15:37

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_usuario', models.CharField(choices=[('A', 'Adotante'), ('R', 'Responsável')], default='A', max_length=1)),
                ('telefone', models.CharField(max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AplicacaoAdocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovada'), ('R', 'Rejeitada'), ('C', 'Cancelada')], default='P', max_length=1)),
                ('motivacao', models.TextField()),
                ('outros_animais', models.BooleanField(default=False)),
                ('tipo_moradia', models.CharField(choices=[('A', 'Apartamento'), ('C', 'Casa'), ('O', 'Outro')], max_length=1)),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicacoes_adocao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aplicação de Adoção',
                'verbose_name_plural': 'Aplicações de Adoção',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Espécie',
                'verbose_name_plural': 'Espécies',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('porte', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], max_length=1)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('D', 'Disponível'), ('A', 'Em Andamento'), ('C', 'Adotado')], default='D', max_length=1)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pets/')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TermoAdocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adocao', models.DateField()),
                ('termos_aceitos', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('aplicacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='termo_adocao', to='adocao.aplicacaoadocao')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termo_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Termo de Adoção',
                'verbose_name_plural': 'Termos de Adoção',
                'ordering': ['-data_adocao'],
            },
        ),
        migrations.CreateModel(
            name='RegistroMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Vacina', 'Vacina'), ('Consulta', 'Consulta'), ('Exame', 'Exame'), ('Medicação', 'Medicação'), ('Cirurgia', 'Cirurgia'), ('Castração', 'Castração'), ('Outro', 'Outro')], max_length=15)),
                ('data', models.DateField()),
                ('descricao_outro', models.CharField(blank=True, max_length=100)),
                ('descricao', models.TextField()),
                ('veterinario', models.CharField(blank=True, max_length=100)),
                ('clinica', models.CharField(blank=True, max_length=100)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_medicos', to='adocao.pet')),
            ],
            options={
                'verbose_name': 'Registro Médico',
                'verbose_name_plural': 'Registros Médicos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racas', to='adocao.especie')),
            ],
            options={
                'verbose_name': 'Raça',
                'verbose_name_plural': 'Raças',
                'ordering': ['nome'],
                'unique_together': {('nome', 'especie')},
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='raca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='adocao.raca'),
        ),
        migrations.AddField(
            model_name='pet',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['usuario'],
            },
        ),
        migrations.CreateModel(
            name='CronogramaVisita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('local', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('A', 'Agendada'), ('R', 'Realizada'), ('C', 'Cancelada')], default='A', max_length=1)),
                ('observacoes', models.TextField(blank=True)),
                ('aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='adocao.aplicacaoadocao')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-data', 'horario'],
            },
        ),
        migrations.AddField(
            model_name='aplicacaoadocao',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicacoes_adocao', to='adocao.pet'),
        ),
        migrations.AlterUniqueTogether(
            name='aplicacaoadocao',
            unique_together={('pet', 'adotante')},
        ),
    ]
