# Generated by Django 3.1.7 on 2026-09-30 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('porte', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], max_length=1)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('D', 'Disponível'), ('A', 'Em Andamento'), ('C', 'Adotado')], default='Disponível', max_length=1)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='adocao.raca')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
