# Generated by Django 3.1.7 on 2026-10-01 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0002_pet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['nome'], 'verbose_name': 'Pet', 'verbose_name_plural': 'Pets'},
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('D', 'Disponível'), ('A', 'Em Andamento'), ('C', 'Adotado')], default='D', max_length=1),
        ),
        migrations.CreateModel(
            name='RegistroMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Vacina', 'Vacina'), ('Consulta', 'Consulta'), ('Exame', 'Exame'), ('Medicação', 'Medicação'), ('Cirurgia', 'Cirurgia'), ('Castração', 'Castração'), ('Outro', 'Outro')], max_length=15)),
                ('data', models.DateField()),
                ('descricao_outro', models.CharField(blank=True, max_length=100)),
                ('descricao', models.TextField()),
                ('veterinario', models.CharField(blank=True, max_length=100)),
                ('clinica', models.CharField(blank=True, max_length=100)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_medicos', to='adocao.pet')),
            ],
            options={
                'verbose_name': 'Registro Médico',
                'verbose_name_plural': 'Registros Médicos',
                'ordering': ['-data'],
            },
        ),
    ]
