# Generated by Django 3.1.7 on 2026-10-01 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0003_auto_20260930_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronogramaVisita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('local', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('A', 'Agendada'), ('R', 'Realizada'), ('C', 'Cancelada')], default='A', max_length=1)),
                ('observacoes', models.TextField(blank=True)),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='adocao.pet')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-data', 'horario'],
            },
        ),
    ]
