# Generated by Django 3.1.7 on 2026-10-01 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0004_cronogramavisita'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoAdocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adocao', models.DateField()),
                ('termos_aceitos', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termo_adotante', to=settings.AUTH_USER_MODEL)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='termo_adocao', to='adocao.pet')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termo_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Termo de Adoção',
                'verbose_name_plural': 'Termos de Adoção',
                'ordering': ['-data_adocao'],
            },
        ),
    ]
