# Generated by Django 3.1.7 on 2026-10-01 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0005_termoadocao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especie',
            options={'ordering': ['nome'], 'verbose_name': 'Espécie', 'verbose_name_plural': 'Espécies'},
        ),
        migrations.AlterModelOptions(
            name='raca',
            options={'ordering': ['nome'], 'verbose_name': 'Raça', 'verbose_name_plural': 'Raças'},
        ),
        migrations.CreateModel(
            name='AplicacaoAdocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovada'), ('R', 'Rejeitada'), ('C', 'Cancelada')], default='P', max_length=1)),
                ('observacoes', models.TextField(blank=True)),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicacoes_adocao', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicacoes_adocao', to='adocao.pet')),
            ],
            options={
                'verbose_name': 'Aplicação de Adoção',
                'verbose_name_plural': 'Aplicações de Adoção',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
